### ISSUE TITLE
Waarom gebruik je geen XML parser?

### ISSUE THREAD

**Issue by Firesphere** [taddeus/tvgids#1]
Je kan de HTML parsen naar XML, dan hoef je niet meer de preg_match zooi te gebruiken en werkt alles een stuk netter.

Daarnaast heeft tvgids.nl hun html aangepast, dus je matcher werkt niet meer ;)

**Comment by taddeus** [comment]
Omdat dat script even snel in elkaar gesleuteld is en niet in productiecode draait ;-)
Daarnaast is een pattern match ruim voldoende in dit geval, aangezien er geen geneste structuren oid hoeven worden herkend.

Ik moet hem inderdaad wel even updaten zie ik
